# Generated by Django 3.2.7 on 2021-11-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_personal_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.CharField(max_length=10, verbose_name='Edad')),
                ('subjects', models.CharField(max_length=10, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
            },
        ),
        migrations.CreateModel(
            name='NoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.CharField(max_length=10, verbose_name='Edad')),
                ('office', models.CharField(max_length=10, verbose_name='Oficina')),
            ],
            options={
                'verbose_name': 'NoDocente',
                'verbose_name_plural': 'NoDocentes',
            },
        ),
        migrations.AlterModelOptions(
            name='establecimientoeducativo',
            options={'ordering': ['name'], 'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
