# Generated by Django 3.2.7 on 2021-11-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_auto_20211130_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='subjects',
            field=models.CharField(max_length=100, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='nodocente',
            name='office',
            field=models.CharField(max_length=100, verbose_name='Oficina'),
        ),
    ]
