# Generated by Django 3.2.7 on 2021-11-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_auto_20211130_0152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.CharField(max_length=10, verbose_name='Edad')),
                ('job', models.CharField(choices=[('0', 'Docente'), ('1', 'No Docente')], max_length=50, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personal',
            },
        ),
        migrations.DeleteModel(
            name='Docente',
        ),
        migrations.DeleteModel(
            name='NoDocente',
        ),
        migrations.AlterModelOptions(
            name='establecimientoeducativo',
            options={'ordering': ['name'], 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
