# Generated by Django 3.2.7 on 2021-11-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0007_alter_personal_job'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personales'},
        ),
        migrations.AlterField(
            model_name='personal',
            name='job',
            field=models.CharField(choices=[('1', 'No Docente'), ('0', 'Docente')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='years',
            field=models.IntegerField(),
        ),
    ]
