# Generated by Django 3.2.7 on 2021-12-01 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0008_auto_20211130_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Personal', 'verbose_name_plural': 'Personales'},
        ),
        migrations.AddField(
            model_name='personal',
            name='materia',
            field=models.CharField(choices=[('0', 'Programacion 1'), ('2', 'Practica 1'), ('1', 'Ingenieria de Software'), ('3', 'Base de datos')], max_length=50, null=True, unique=True, verbose_name='Materia'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='years',
            field=models.IntegerField(verbose_name='Edad'),
        ),
    ]
