# Generated by Django 3.2.7 on 2021-12-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0009_auto_20211201_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='materia',
            field=models.CharField(choices=[('0', 'Programacion 1'), ('1', 'Ingenieria de Software'), ('3', 'Base de datos'), ('2', 'Practica 1')], max_length=50, null=True, unique=True, verbose_name='Materia'),
        ),
    ]
