# Generated by Django 3.2.7 on 2021-12-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0010_alter_personal_materia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal',
            name='job',
            field=models.CharField(choices=[('0', 'Docente'), ('1', 'No Docente')], max_length=50, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='materia',
            field=models.CharField(choices=[('2', 'Practica 1'), ('0', 'Programacion 1'), ('3', 'Base de datos'), ('1', 'Ingenieria de Software')], max_length=50, null=True, unique=True, verbose_name='Materia'),
        ),
    ]
