# Generated by Django 3.2.7 on 2021-12-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0011_auto_20211201_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='oficina',
            field=models.CharField(choices=[('1', 'Direccion'), ('2', 'Coordinadocion'), ('3', 'Ayudante'), ('0', 'Preceptoria')], max_length=50, null=True, unique=True, verbose_name='Oficina'),
        ),
        migrations.AlterField(
            model_name='personal',
            name='materia',
            field=models.CharField(choices=[('1', 'Ingenieria de Software'), ('3', 'Base de datos'), ('0', 'Programacion 1'), ('2', 'Practica 1')], max_length=50, null=True, unique=True, verbose_name='Materia'),
        ),
    ]
