# Generated by Django 3.2.7 on 2021-12-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0012_auto_20211201_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='oficina',
        ),
        migrations.AddField(
            model_name='personal',
            name='valor_materia',
            field=models.CharField(blank=True, choices=[('0', 'Programacion 1'), ('1', 'Ingenieria de Software'), ('2', 'Practica 1'), ('3', 'Base de datos')], max_length=50, null=True, unique=True, verbose_name='Materia'),
        ),
        migrations.AddField(
            model_name='personal',
            name='valor_oficina',
            field=models.CharField(blank=True, choices=[('0', 'Preceptoria'), ('1', 'Direccion'), ('2', 'Coordinadocion'), ('3', 'Ayudante')], max_length=50, null=True, unique=True, verbose_name='Oficina'),
        ),
    ]
