# Generated by Django 3.2.7 on 2021-12-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0013_auto_20211209_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.IntegerField(verbose_name='Edad')),
                ('materia', models.CharField(blank=True, choices=[('0', 'Programacion 1'), ('1', 'Ingenieria de Software'), ('2', 'Practica 1'), ('3', 'Base de datos')], max_length=50, null=True, unique=True, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'PersonalDocentes',
                'verbose_name_plural': 'PersonalDocente',
            },
        ),
        migrations.DeleteModel(
            name='Personal',
        ),
    ]
