# Generated by Django 3.2.7 on 2021-12-10 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0014_auto_20211210_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalNoDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido')),
                ('years', models.IntegerField(verbose_name='Edad')),
                ('oficina', models.CharField(blank=True, choices=[('0', 'Dirección'), ('1', 'Preceptoria'), ('2', 'Coordinacion'), ('3', 'Ayudantia'), ('4', 'Desbloqueo de Netbook')], max_length=50, null=True, unique=True, verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'PersonalNoDocentes',
                'verbose_name_plural': 'PersonalNoDocente',
            },
        ),
    ]
