# Generated by Django 3.2.7 on 2021-12-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0015_personalnodocente'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstablecimientoEducativo2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('short_name', models.CharField(max_length=50, verbose_name='Nombre corto')),
            ],
            options={
                'verbose_name': 'Oficina',
                'verbose_name_plural': 'Oficinas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='establecimientoeducativo',
            options={'ordering': ['name'], 'verbose_name': 'Materia', 'verbose_name_plural': 'Materias'},
        ),
        migrations.RemoveField(
            model_name='personaldocente',
            name='materia',
        ),
        migrations.RemoveField(
            model_name='personalnodocente',
            name='oficina',
        ),
    ]
