# Generated by Django 3.2.7 on 2021-12-16 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0016_auto_20211216_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldocente',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.establecimientoeducativo'),
        ),
        migrations.AddField(
            model_name='personalnodocente',
            name='oficina',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registro.establecimientoeducativo2'),
        ),
    ]
