# Generated by Django 3.2.7 on 2021-12-17 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0017_auto_20211216_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldocente',
            name='perfil',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen de Perfil'),
        ),
        migrations.AddField(
            model_name='personalnodocente',
            name='perfil',
            field=models.ImageField(blank=True, upload_to='registro', verbose_name='Imagen de Perfil'),
        ),
    ]
